// Comprehensive KPI Library organized by data source and question context

export interface KPI {
  id: string;
  name: string;
  label: string;
  description: string;
  category: 'promotion' | 'financial' | 'customer' | 'inventory' | 'marketing' | 'competitive' | 'store' | 'product';
  dataSource: string[];
  format: 'currency' | 'percent' | 'number' | 'ratio';
  calculation?: string;
}

export const kpiLibrary: KPI[] = [
  // Promotion KPIs
  { id: 'roi', name: 'ROI', label: 'Return on Investment', description: 'Revenue generated per dollar spent on promotion', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'ratio', calculation: 'revenue / total_spend' },
  { id: 'lift_pct', name: 'Lift %', label: 'Sales Lift Percentage', description: 'Percentage increase in sales during promotion vs baseline', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'percent', calculation: '(promo_sales - baseline_sales) / baseline_sales * 100' },
  { id: 'incremental_margin', name: 'Incremental Margin', label: 'Incremental Margin', description: 'Additional profit generated by the promotion', category: 'promotion', dataSource: ['promotions', 'transactions', 'products'], format: 'currency', calculation: 'incremental_revenue * margin_pct' },
  { id: 'promo_spend', name: 'Promo Spend', label: 'Promotion Spend', description: 'Total cost invested in the promotion', category: 'promotion', dataSource: ['promotions'], format: 'currency' },
  { id: 'discount_depth', name: 'Discount Depth', label: 'Discount Depth', description: 'Percentage discount offered', category: 'promotion', dataSource: ['promotions'], format: 'percent' },
  { id: 'redemption_rate', name: 'Redemption Rate', label: 'Coupon Redemption Rate', description: 'Percentage of coupons redeemed', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'percent' },
  { id: 'promo_effectiveness', name: 'Effectiveness', label: 'Promotion Effectiveness Score', description: 'Composite score measuring overall promotion success', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'ratio' },
  
  // Financial KPIs
  { id: 'revenue', name: 'Revenue', label: 'Total Revenue', description: 'Total sales revenue generated', category: 'financial', dataSource: ['transactions'], format: 'currency' },
  { id: 'gross_margin', name: 'Gross Margin', label: 'Gross Margin', description: 'Revenue minus cost of goods sold', category: 'financial', dataSource: ['transactions', 'products'], format: 'currency' },
  { id: 'margin_pct', name: 'Margin %', label: 'Margin Percentage', description: 'Gross margin as percentage of revenue', category: 'financial', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'aov', name: 'AOV', label: 'Average Order Value', description: 'Average transaction value', category: 'financial', dataSource: ['transactions'], format: 'currency' },
  { id: 'units_sold', name: 'Units Sold', label: 'Units Sold', description: 'Total quantity of items sold', category: 'financial', dataSource: ['transactions'], format: 'number' },
  { id: 'cost', name: 'Cost', label: 'Total Cost', description: 'Total cost of goods sold', category: 'financial', dataSource: ['products', 'transactions'], format: 'currency' },
  { id: 'profit', name: 'Profit', label: 'Net Profit', description: 'Revenue minus all costs', category: 'financial', dataSource: ['transactions', 'products', 'promotions'], format: 'currency' },
  
  // Customer KPIs
  { id: 'customer_count', name: 'Customers', label: 'Customer Count', description: 'Number of unique customers', category: 'customer', dataSource: ['customers', 'transactions'], format: 'number' },
  { id: 'clv', name: 'CLV', label: 'Customer Lifetime Value', description: 'Total expected revenue from a customer', category: 'customer', dataSource: ['customers'], format: 'currency' },
  { id: 'retention_rate', name: 'Retention', label: 'Retention Rate', description: 'Percentage of customers who return', category: 'customer', dataSource: ['customers', 'transactions'], format: 'percent' },
  { id: 'conversion_rate', name: 'Conversion', label: 'Conversion Rate', description: 'Percentage of visitors who purchase', category: 'customer', dataSource: ['customer_journey', 'transactions'], format: 'percent' },
  { id: 'churn_rate', name: 'Churn', label: 'Churn Rate', description: 'Percentage of customers lost', category: 'customer', dataSource: ['customers', 'transactions'], format: 'percent' },
  { id: 'segment_penetration', name: 'Penetration', label: 'Segment Penetration', description: 'Percentage of segment reached by promotion', category: 'customer', dataSource: ['customers', 'transactions', 'promotions'], format: 'percent' },
  { id: 'loyalty_tier_distribution', name: 'Loyalty Dist', label: 'Loyalty Distribution', description: 'Breakdown of customers by loyalty tier', category: 'customer', dataSource: ['customers'], format: 'percent' },
  
  // Inventory KPIs
  { id: 'stock_level', name: 'Stock Level', label: 'Current Stock Level', description: 'Current inventory quantity', category: 'inventory', dataSource: ['inventory_levels'], format: 'number' },
  { id: 'stockout_risk', name: 'Stockout Risk', label: 'Stockout Risk', description: 'Risk level of running out of stock', category: 'inventory', dataSource: ['inventory_levels'], format: 'percent' },
  { id: 'turnover_rate', name: 'Turnover', label: 'Inventory Turnover', description: 'How quickly inventory is sold', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'ratio' },
  { id: 'days_on_hand', name: 'Days on Hand', label: 'Days of Inventory', description: 'Number of days current inventory will last', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'number' },
  
  // Marketing KPIs
  { id: 'impressions', name: 'Impressions', label: 'Total Impressions', description: 'Number of times ad was shown', category: 'marketing', dataSource: ['marketing_channels'], format: 'number' },
  { id: 'clicks', name: 'Clicks', label: 'Total Clicks', description: 'Number of clicks on promotion', category: 'marketing', dataSource: ['marketing_channels'], format: 'number' },
  { id: 'ctr', name: 'CTR', label: 'Click-Through Rate', description: 'Percentage of impressions that result in clicks', category: 'marketing', dataSource: ['marketing_channels'], format: 'percent' },
  { id: 'cpc', name: 'CPC', label: 'Cost Per Click', description: 'Average cost for each click', category: 'marketing', dataSource: ['marketing_channels'], format: 'currency' },
  { id: 'cpa', name: 'CPA', label: 'Cost Per Acquisition', description: 'Cost to acquire one customer', category: 'marketing', dataSource: ['marketing_channels', 'transactions'], format: 'currency' },
  { id: 'roas', name: 'ROAS', label: 'Return on Ad Spend', description: 'Revenue generated per dollar of ad spend', category: 'marketing', dataSource: ['marketing_channels', 'transactions'], format: 'ratio' },
  { id: 'engagement_rate', name: 'Engagement', label: 'Engagement Rate', description: 'Percentage of audience that engaged', category: 'marketing', dataSource: ['marketing_channels'], format: 'percent' },
  { id: 'reach', name: 'Reach', label: 'Total Reach', description: 'Number of unique people reached', category: 'marketing', dataSource: ['marketing_channels'], format: 'number' },
  
  // Competitive KPIs
  { id: 'market_share', name: 'Market Share', label: 'Market Share', description: 'Percentage of total market captured', category: 'competitive', dataSource: ['competitor_data', 'transactions'], format: 'percent' },
  { id: 'price_index', name: 'Price Index', label: 'Price Index vs Competitors', description: 'Price comparison to competitors', category: 'competitive', dataSource: ['competitor_data', 'products'], format: 'ratio' },
  { id: 'promo_intensity', name: 'Promo Intensity', label: 'Competitive Promo Intensity', description: 'Level of competitor promotional activity', category: 'competitive', dataSource: ['competitor_data'], format: 'percent' },
  { id: 'share_gain', name: 'Share Gain', label: 'Market Share Gain', description: 'Change in market share', category: 'competitive', dataSource: ['competitor_data'], format: 'percent' },
  
  // Store KPIs
  { id: 'store_sales', name: 'Store Sales', label: 'Store Sales', description: 'Total sales by store', category: 'store', dataSource: ['store_performance', 'transactions'], format: 'currency' },
  { id: 'foot_traffic', name: 'Foot Traffic', label: 'Foot Traffic', description: 'Number of store visitors', category: 'store', dataSource: ['store_performance'], format: 'number' },
  { id: 'basket_size', name: 'Basket Size', label: 'Average Basket Size', description: 'Average items per transaction', category: 'store', dataSource: ['store_performance', 'transactions'], format: 'number' },
  { id: 'store_conversion', name: 'Store Conversion', label: 'Store Conversion Rate', description: 'Percentage of visitors who purchase', category: 'store', dataSource: ['store_performance'], format: 'percent' },
  { id: 'sales_per_sqft', name: 'Sales/SqFt', label: 'Sales per Square Foot', description: 'Revenue per square foot of store space', category: 'store', dataSource: ['store_performance', 'stores'], format: 'currency' },
  
  // Product KPIs
  { id: 'price_elasticity', name: 'Elasticity', label: 'Price Elasticity', description: 'Sensitivity of demand to price changes', category: 'product', dataSource: ['products', 'transactions'], format: 'ratio' },
  { id: 'category_share', name: 'Category Share', label: 'Category Share', description: 'Percentage of category sales', category: 'product', dataSource: ['products', 'transactions'], format: 'percent' },
  { id: 'halo_effect', name: 'Halo Effect', label: 'Halo Effect', description: 'Sales lift in related products', category: 'product', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'cannibalization', name: 'Cannibalization', label: 'Cannibalization Rate', description: 'Sales taken from other products', category: 'product', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'brand_share', name: 'Brand Share', label: 'Brand Market Share', description: 'Brand percentage of category sales', category: 'product', dataSource: ['products', 'transactions'], format: 'percent' },
];

// Question context to KPI mapping
export const questionContextKPIs: Record<string, string[]> = {
  // ROI and Performance Questions
  'roi': ['roi', 'lift_pct', 'incremental_margin', 'promo_spend', 'revenue', 'gross_margin'],
  'performance': ['roi', 'lift_pct', 'revenue', 'units_sold', 'margin_pct', 'promo_effectiveness'],
  'top': ['roi', 'lift_pct', 'incremental_margin', 'revenue', 'gross_margin'],
  'best': ['roi', 'lift_pct', 'incremental_margin', 'promo_effectiveness'],
  'worst': ['roi', 'lift_pct', 'incremental_margin', 'promo_spend'],
  'underperforming': ['roi', 'lift_pct', 'promo_spend', 'gross_margin'],
  'lost money': ['roi', 'incremental_margin', 'promo_spend', 'gross_margin', 'profit'],
  
  // Financial Questions
  'revenue': ['revenue', 'gross_margin', 'margin_pct', 'aov', 'units_sold'],
  'margin': ['gross_margin', 'margin_pct', 'incremental_margin', 'profit', 'cost'],
  'profit': ['profit', 'gross_margin', 'revenue', 'cost', 'margin_pct'],
  'spend': ['promo_spend', 'roi', 'cpa', 'roas', 'cpc'],
  'cost': ['cost', 'promo_spend', 'cpc', 'cpa', 'gross_margin'],
  
  // Promotion Mechanics Questions
  'discount': ['discount_depth', 'roi', 'lift_pct', 'incremental_margin', 'redemption_rate'],
  'coupon': ['redemption_rate', 'roi', 'promo_spend', 'conversion_rate', 'cpa'],
  'bogo': ['lift_pct', 'roi', 'units_sold', 'incremental_margin', 'cannibalization'],
  'mechanic': ['roi', 'lift_pct', 'redemption_rate', 'conversion_rate', 'promo_effectiveness'],
  'depth': ['discount_depth', 'roi', 'lift_pct', 'price_elasticity', 'margin_pct'],
  
  // Customer Questions
  'customer': ['customer_count', 'clv', 'retention_rate', 'segment_penetration', 'conversion_rate'],
  'segment': ['segment_penetration', 'clv', 'customer_count', 'aov', 'retention_rate'],
  'loyalty': ['loyalty_tier_distribution', 'clv', 'retention_rate', 'aov', 'customer_count'],
  'churn': ['churn_rate', 'retention_rate', 'clv', 'customer_count'],
  'acquisition': ['cpa', 'conversion_rate', 'customer_count', 'clv', 'roas'],
  
  // Marketing Questions
  'marketing': ['impressions', 'clicks', 'ctr', 'engagement_rate', 'reach', 'roas'],
  'channel': ['roas', 'cpa', 'conversion_rate', 'engagement_rate', 'reach'],
  'campaign': ['roi', 'impressions', 'clicks', 'conversion_rate', 'roas'],
  'advertising': ['impressions', 'ctr', 'cpc', 'roas', 'reach'],
  
  // Inventory Questions
  'inventory': ['stock_level', 'stockout_risk', 'turnover_rate', 'days_on_hand'],
  'stock': ['stock_level', 'stockout_risk', 'turnover_rate', 'units_sold'],
  'stockout': ['stockout_risk', 'stock_level', 'turnover_rate', 'days_on_hand'],
  
  // Competitive Questions
  'competitor': ['market_share', 'price_index', 'promo_intensity', 'share_gain'],
  'market share': ['market_share', 'share_gain', 'category_share', 'brand_share'],
  'competitive': ['market_share', 'price_index', 'promo_intensity', 'share_gain'],
  
  // Store Questions
  'store': ['store_sales', 'foot_traffic', 'basket_size', 'store_conversion'],
  'regional': ['store_sales', 'market_share', 'foot_traffic', 'store_conversion'],
  'location': ['store_sales', 'foot_traffic', 'store_conversion', 'basket_size'],
  
  // Product Questions
  'category': ['category_share', 'roi', 'revenue', 'margin_pct', 'units_sold'],
  'brand': ['brand_share', 'roi', 'revenue', 'lift_pct', 'market_share'],
  'sku': ['units_sold', 'revenue', 'margin_pct', 'price_elasticity', 'turnover_rate'],
  'product': ['units_sold', 'revenue', 'price_elasticity', 'category_share', 'margin_pct'],
  
  // Cross-sell & Halo Questions
  'halo': ['halo_effect', 'incremental_margin', 'units_sold', 'category_share'],
  'cannibalization': ['cannibalization', 'incremental_margin', 'category_share', 'units_sold'],
  'cross-sell': ['halo_effect', 'aov', 'basket_size', 'units_sold'],
  'bundle': ['aov', 'basket_size', 'units_sold', 'incremental_margin', 'halo_effect'],
  
  // Forecasting Questions
  'forecast': ['revenue', 'units_sold', 'roi', 'lift_pct', 'margin_pct'],
  'predict': ['roi', 'lift_pct', 'revenue', 'churn_rate', 'conversion_rate'],
  'trend': ['revenue', 'market_share', 'units_sold', 'foot_traffic'],
  'seasonal': ['revenue', 'units_sold', 'lift_pct', 'stock_level'],
  
  // Optimization Questions
  'optimal': ['roi', 'discount_depth', 'incremental_margin', 'price_elasticity'],
  'optimize': ['roi', 'margin_pct', 'promo_effectiveness', 'roas'],
  'maximize': ['roi', 'incremental_margin', 'profit', 'revenue'],
  'minimize': ['cost', 'cpa', 'churn_rate', 'cannibalization'],
};

// Get suggested KPIs based on question text
export function getSuggestedKPIs(question: string): KPI[] {
  const questionLower = question.toLowerCase();
  const suggestedIds = new Set<string>();
  
  // Match against context keywords
  for (const [context, kpiIds] of Object.entries(questionContextKPIs)) {
    if (questionLower.includes(context)) {
      kpiIds.forEach(id => suggestedIds.add(id));
    }
  }
  
  // Default KPIs if no matches
  if (suggestedIds.size === 0) {
    ['roi', 'lift_pct', 'incremental_margin', 'promo_spend', 'revenue'].forEach(id => suggestedIds.add(id));
  }
  
  // Get full KPI objects, limited to 8 suggestions
  return Array.from(suggestedIds)
    .slice(0, 8)
    .map(id => kpiLibrary.find(kpi => kpi.id === id))
    .filter((kpi): kpi is KPI => kpi !== undefined);
}

// Get all KPIs by category
export function getKPIsByCategory(): Record<string, KPI[]> {
  const grouped: Record<string, KPI[]> = {};
  
  for (const kpi of kpiLibrary) {
    if (!grouped[kpi.category]) {
      grouped[kpi.category] = [];
    }
    grouped[kpi.category].push(kpi);
  }
  
  return grouped;
}

// Format KPI value based on format type
export function formatKPIDisplay(value: number, format: KPI['format']): string {
  switch (format) {
    case 'currency':
      if (Math.abs(value) >= 1000000000) return `$${(value / 1000000000).toFixed(1)}B`;
      if (Math.abs(value) >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
      if (Math.abs(value) >= 1000) return `$${(value / 1000).toFixed(0)}K`;
      return `$${value.toFixed(0)}`;
    case 'percent':
      return `${value.toFixed(1)}%`;
    case 'ratio':
      return value.toFixed(2);
    case 'number':
      return value.toLocaleString();
    default:
      return String(value);
  }
}
