// Comprehensive KPI Library organized by data source and question context

export interface KPI {
  id: string;
  name: string;
  label: string;
  description: string;
  category: 'promotion' | 'financial' | 'customer' | 'inventory' | 'marketing' | 'competitive' | 'store' | 'product' | 'supply_chain' | 'space' | 'pricing';
  dataSource: string[];
  format: 'currency' | 'percent' | 'number' | 'ratio';
  calculation?: string;
}

export const kpiLibrary: KPI[] = [
  // Promotion KPIs
  { id: 'roi', name: 'ROI', label: 'Return on Investment', description: 'Revenue generated per dollar spent on promotion', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'ratio' },
  { id: 'lift_pct', name: 'Lift %', label: 'Sales Lift Percentage', description: 'Percentage increase in sales during promotion vs baseline', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'percent' },
  { id: 'incremental_margin', name: 'Incremental Margin', label: 'Incremental Margin', description: 'Additional profit generated by the promotion', category: 'promotion', dataSource: ['promotions', 'transactions', 'products'], format: 'currency' },
  { id: 'promo_spend', name: 'Promo Spend', label: 'Promotion Spend', description: 'Total cost invested in the promotion', category: 'promotion', dataSource: ['promotions'], format: 'currency' },
  { id: 'discount_depth', name: 'Discount Depth', label: 'Discount Depth', description: 'Percentage discount offered', category: 'promotion', dataSource: ['promotions'], format: 'percent' },
  { id: 'redemption_rate', name: 'Redemption Rate', label: 'Coupon Redemption Rate', description: 'Percentage of coupons redeemed', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'percent' },
  { id: 'promo_effectiveness', name: 'Effectiveness', label: 'Promotion Effectiveness Score', description: 'Composite score measuring overall promotion success', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'ratio' },
  { id: 'promo_intensity', name: 'Promo Intensity', label: 'Promo Intensity Index', description: 'Frequency and depth of promotional activity', category: 'promotion', dataSource: ['promotions'], format: 'ratio' },
  { id: 'markdown_efficiency', name: 'Markdown Efficiency', label: 'Markdown Efficiency', description: 'Effectiveness of markdown pricing', category: 'promotion', dataSource: ['promotions', 'transactions'], format: 'percent' },
  
  // Financial KPIs
  { id: 'revenue', name: 'Revenue', label: 'Total Revenue', description: 'Total sales revenue generated', category: 'financial', dataSource: ['transactions'], format: 'currency' },
  { id: 'gross_margin', name: 'Gross Margin', label: 'Gross Margin', description: 'Revenue minus cost of goods sold', category: 'financial', dataSource: ['transactions', 'products'], format: 'currency' },
  { id: 'margin_pct', name: 'Margin %', label: 'Margin Percentage', description: 'Gross margin as percentage of revenue', category: 'financial', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'aov', name: 'AOV', label: 'Average Order Value', description: 'Average transaction value', category: 'financial', dataSource: ['transactions'], format: 'currency' },
  { id: 'units_sold', name: 'Units Sold', label: 'Units Sold', description: 'Total quantity of items sold', category: 'financial', dataSource: ['transactions'], format: 'number' },
  { id: 'gmroi', name: 'GMROI', label: 'Gross Margin Return on Investment', description: 'Gross margin dollars per dollar of inventory', category: 'financial', dataSource: ['transactions', 'inventory_levels'], format: 'ratio' },
  
  // Customer KPIs
  { id: 'customer_count', name: 'Customers', label: 'Customer Count', description: 'Number of unique customers', category: 'customer', dataSource: ['customers', 'transactions'], format: 'number' },
  { id: 'clv', name: 'CLV', label: 'Customer Lifetime Value', description: 'Total expected revenue from a customer', category: 'customer', dataSource: ['customers'], format: 'currency' },
  { id: 'retention_rate', name: 'Retention', label: 'Retention Rate', description: 'Percentage of customers who return', category: 'customer', dataSource: ['customers', 'transactions'], format: 'percent' },
  { id: 'conversion_rate', name: 'Conversion', label: 'Conversion Rate', description: 'Percentage of visitors who purchase', category: 'customer', dataSource: ['customer_journey', 'transactions'], format: 'percent' },
  { id: 'basket_penetration', name: 'Basket Penetration', label: 'Basket Penetration', description: 'Percentage of baskets containing category/product', category: 'customer', dataSource: ['transactions'], format: 'percent' },
  
  // Inventory KPIs - Critical Merchandising Metrics
  { id: 'stock_level', name: 'Stock Level', label: 'Current Stock Level', description: 'Current inventory quantity', category: 'inventory', dataSource: ['inventory_levels'], format: 'number' },
  { id: 'stockout_risk', name: 'Stockout Risk', label: 'Stockout Risk', description: 'Risk level of running out of stock', category: 'inventory', dataSource: ['inventory_levels'], format: 'percent' },
  { id: 'turnover_rate', name: 'Turnover', label: 'Inventory Turnover', description: 'How quickly inventory is sold', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'ratio' },
  { id: 'days_on_hand', name: 'Days on Hand', label: 'Days of Inventory', description: 'Number of days current inventory will last', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'number' },
  { id: 'sell_through_rate', name: 'Sell-Through Rate', label: 'Sell-Through Rate', description: 'Percentage of received inventory sold (Units Sold / Units Received)', category: 'inventory', dataSource: ['transactions', 'supplier_orders'], format: 'percent', calculation: '(units_sold / units_received) * 100' },
  { id: 'weeks_of_supply', name: 'Weeks of Supply', label: 'Weeks of Supply', description: 'Number of weeks current inventory will last', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'number' },
  { id: 'safety_stock', name: 'Safety Stock', label: 'Safety Stock Level', description: 'Buffer inventory to prevent stockouts', category: 'inventory', dataSource: ['inventory_levels'], format: 'number' },
  { id: 'service_level', name: 'Service Level', label: 'Service Level', description: 'Probability of not stocking out', category: 'inventory', dataSource: ['inventory_levels'], format: 'percent' },
  { id: 'dead_stock_pct', name: 'Dead Stock %', label: 'Dead Stock Percentage', description: 'Percentage of inventory with no sales', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'percent' },
  { id: 'fill_rate', name: 'Fill Rate', label: 'Fill Rate', description: 'Percentage of customer demand fulfilled from stock', category: 'inventory', dataSource: ['inventory_levels', 'transactions'], format: 'percent' },
  
  // Competitive KPIs
  { id: 'market_share', name: 'Market Share', label: 'Market Share', description: 'Percentage of total market captured', category: 'competitive', dataSource: ['competitor_data', 'transactions'], format: 'percent' },
  { id: 'price_index', name: 'Price Index', label: 'Price Index vs Competitors', description: 'Price comparison to competitors', category: 'competitive', dataSource: ['competitor_data', 'products'], format: 'ratio' },
  
  // Store KPIs
  { id: 'store_sales', name: 'Store Sales', label: 'Store Sales', description: 'Total sales by store', category: 'store', dataSource: ['store_performance', 'transactions'], format: 'currency' },
  { id: 'foot_traffic', name: 'Foot Traffic', label: 'Foot Traffic', description: 'Number of store visitors', category: 'store', dataSource: ['store_performance'], format: 'number' },
  { id: 'basket_size', name: 'Basket Size', label: 'Average Basket Size', description: 'Average items per transaction', category: 'store', dataSource: ['store_performance', 'transactions'], format: 'number' },
  { id: 'store_conversion', name: 'Store Conversion', label: 'Store Conversion Rate', description: 'Percentage of visitors who purchase', category: 'store', dataSource: ['store_performance'], format: 'percent' },
  { id: 'sales_per_sqft', name: 'Sales/SqFt', label: 'Sales per Square Foot', description: 'Revenue per square foot of store space', category: 'store', dataSource: ['store_performance', 'stores'], format: 'currency' },
  { id: 'units_per_transaction', name: 'UPT', label: 'Units per Transaction', description: 'Average units sold per transaction', category: 'store', dataSource: ['transactions'], format: 'ratio' },
  
  // Product KPIs
  { id: 'price_elasticity', name: 'Elasticity', label: 'Price Elasticity', description: 'Sensitivity of demand to price changes', category: 'product', dataSource: ['products', 'transactions'], format: 'ratio' },
  { id: 'category_share', name: 'Category Share', label: 'Category Share', description: 'Percentage of category sales', category: 'product', dataSource: ['products', 'transactions'], format: 'percent' },
  { id: 'halo_effect', name: 'Halo Effect', label: 'Halo Effect', description: 'Sales lift in related products', category: 'product', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'cannibalization', name: 'Cannibalization', label: 'Cannibalization Rate', description: 'Sales taken from other products', category: 'product', dataSource: ['transactions', 'products'], format: 'percent' },
  { id: 'sku_productivity', name: 'SKU Productivity', label: 'SKU Productivity', description: 'Revenue per active SKU', category: 'product', dataSource: ['products', 'transactions'], format: 'currency' },
  
  // Supply Chain KPIs
  { id: 'on_time_delivery', name: 'OTD', label: 'On-Time Delivery', description: 'Percentage of orders delivered on time', category: 'supply_chain', dataSource: ['supplier_orders'], format: 'percent' },
  { id: 'supplier_fill_rate', name: 'Supplier Fill Rate', label: 'Supplier Fill Rate', description: 'Percentage of orders fully fulfilled by supplier', category: 'supply_chain', dataSource: ['supplier_orders'], format: 'percent' },
  { id: 'lead_time', name: 'Lead Time', label: 'Lead Time (Days)', description: 'Days from order to delivery', category: 'supply_chain', dataSource: ['suppliers', 'supplier_orders'], format: 'number' },
  { id: 'vendor_scorecard', name: 'Vendor Score', label: 'Vendor Scorecard', description: 'Overall vendor performance score', category: 'supply_chain', dataSource: ['suppliers'], format: 'ratio' },
  
  // Space Planning KPIs
  { id: 'gmrof', name: 'GMROF', label: 'Gross Margin Return on Footage', description: 'Gross margin per linear foot of shelf space', category: 'space', dataSource: ['shelf_allocations', 'transactions'], format: 'ratio' },
  { id: 'share_of_shelf', name: 'Share of Shelf', label: 'Share of Shelf', description: 'Percentage of shelf space allocated', category: 'space', dataSource: ['shelf_allocations'], format: 'percent' },
  { id: 'planogram_compliance', name: 'POG Compliance', label: 'Planogram Compliance', description: 'Adherence to planned shelf layout', category: 'space', dataSource: ['planograms'], format: 'percent' },
  
  // Pricing KPIs
  { id: 'net_price_realization', name: 'Net Price', label: 'Net Price Realization', description: 'Actual selling price after discounts', category: 'pricing', dataSource: ['transactions'], format: 'percent' },
  { id: 'cross_elasticity', name: 'Cross Elasticity', label: 'Cross-Price Elasticity', description: 'Impact of one product price on another product demand', category: 'pricing', dataSource: ['products', 'transactions'], format: 'ratio' },
  { id: 'avg_discount', name: 'Avg Discount', label: 'Average Discount %', description: 'Average discount given across transactions', category: 'pricing', dataSource: ['transactions'], format: 'percent' },
];

// Question context to KPI mapping
export const questionContextKPIs: Record<string, string[]> = {
  'roi': ['roi', 'lift_pct', 'incremental_margin', 'promo_spend', 'revenue', 'gross_margin'],
  'performance': ['roi', 'lift_pct', 'revenue', 'units_sold', 'margin_pct', 'promo_effectiveness'],
  'top': ['roi', 'lift_pct', 'incremental_margin', 'revenue', 'gross_margin'],
  'best': ['roi', 'lift_pct', 'incremental_margin', 'promo_effectiveness'],
  'revenue': ['revenue', 'gross_margin', 'margin_pct', 'aov', 'units_sold'],
  'margin': ['gross_margin', 'margin_pct', 'incremental_margin'],
  'inventory': ['stock_level', 'stockout_risk', 'turnover_rate', 'days_on_hand', 'sell_through_rate', 'weeks_of_supply'],
  'stock': ['stock_level', 'stockout_risk', 'turnover_rate', 'units_sold', 'sell_through_rate'],
  'sell-through': ['sell_through_rate', 'units_sold', 'stock_level', 'turnover_rate'],
  'sell through': ['sell_through_rate', 'units_sold', 'stock_level', 'turnover_rate'],
  'weeks of supply': ['weeks_of_supply', 'days_on_hand', 'stock_level', 'turnover_rate'],
  'customer': ['customer_count', 'clv', 'retention_rate', 'conversion_rate', 'basket_penetration'],
  'store': ['store_sales', 'foot_traffic', 'basket_size', 'store_conversion', 'units_per_transaction'],
  'category': ['category_share', 'roi', 'revenue', 'margin_pct', 'units_sold', 'basket_penetration'],
  'sku': ['units_sold', 'revenue', 'margin_pct', 'turnover_rate', 'sku_productivity', 'sell_through_rate'],
  'product': ['units_sold', 'revenue', 'price_elasticity', 'category_share', 'margin_pct'],
  'supplier': ['on_time_delivery', 'supplier_fill_rate', 'lead_time', 'vendor_scorecard'],
  'shelf': ['share_of_shelf', 'gmrof', 'planogram_compliance', 'sales_per_sqft'],
  'price': ['price_elasticity', 'net_price_realization', 'price_index', 'avg_discount', 'cross_elasticity'],
};

export function getSuggestedKPIs(question: string): KPI[] {
  const questionLower = question.toLowerCase();
  const suggestedIds = new Set<string>();
  
  for (const [context, kpiIds] of Object.entries(questionContextKPIs)) {
    if (questionLower.includes(context)) {
      kpiIds.forEach(id => suggestedIds.add(id));
    }
  }
  
  if (suggestedIds.size === 0) {
    ['roi', 'lift_pct', 'incremental_margin', 'promo_spend', 'revenue'].forEach(id => suggestedIds.add(id));
  }
  
  return Array.from(suggestedIds)
    .slice(0, 8)
    .map(id => kpiLibrary.find(kpi => kpi.id === id))
    .filter((kpi): kpi is KPI => kpi !== undefined);
}

export function getKPIsByCategory(): Record<string, KPI[]> {
  const grouped: Record<string, KPI[]> = {};
  for (const kpi of kpiLibrary) {
    if (!grouped[kpi.category]) grouped[kpi.category] = [];
    grouped[kpi.category].push(kpi);
  }
  return grouped;
}

export function formatKPIDisplay(value: number, format: KPI['format']): string {
  switch (format) {
    case 'currency':
      if (Math.abs(value) >= 1000000000) return `$${(value / 1000000000).toFixed(1)}B`;
      if (Math.abs(value) >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
      if (Math.abs(value) >= 1000) return `$${(value / 1000).toFixed(0)}K`;
      return `$${value.toFixed(0)}`;
    case 'percent': return `${value.toFixed(1)}%`;
    case 'ratio': return value.toFixed(2);
    case 'number': return value.toLocaleString();
    default: return String(value);
  }
}